### ISSUE TITLE
Trello Road map link not working 

### ISSUE THREAD

**Issue by MostafaNawara** [daedlock/MovieMate#1]
The [Trello]( https://trello.com/b/D2npB3XP/moviemate) link is not working.

![capture](https://cloud.githubusercontent.com/assets/3069041/21124201/176b8504-c0e6-11e6-95b5-7fda60e68dc4.PNG)

**Comment by daedlock** [comment]
It was private. Updated the board link in `README.md`

https://trello.com/b/yhLFm248/moviemate-roadmap
